from os import path
import pandas as pd
from pathlib import Path
import matplotlib

# Force matplotlib to not use any Xwindows backend / GUI framework
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def plot_hmm_metrics(csv_path):
    # Load the training metrics generated by your C++ code
    df = pd.read_csv(csv_path)

    # PLOT 1: Hill-Climbing
    plt.figure(figsize=(10, 6))
    plt.plot(df["k"], df["train_log_prob"], label="Training Set A", color="blue")
    plt.plot(
        df["k"], df["test_log_prob"], label="Test Set B", color="red", linestyle="--"
    )

    plt.title("Average Log-Probability vs Iterations (k)")
    plt.xlabel("Iteration (k)")
    plt.ylabel("Average Log-Probability")
    plt.legend()
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.savefig("hill_climbing_plot.png")
    plt.close()  # Close the figure to free memory

    # PLOT 2: Emission Probabilities for 'a', 'n', and ' '
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))

    # Subplot 1 for a
    ax1.plot(df["k"], df["q_a_0"], label="State 1 (q(a|1))", color="green")
    ax1.plot(df["k"], df["q_a_1"], label="State 2 (q(a|2))", color="orange")
    ax1.set_title("Emission Probabilities for 'a'")
    ax1.set_xlabel("Iteration (k)")
    ax1.set_ylabel("Probability")
    ax1.legend()
    ax1.grid(True, linestyle=":", alpha=0.6)

    # Subplot 2 for n
    ax2.plot(df["k"], df["q_n_0"], label="State 1 (q(n|1))", color="purple")
    ax2.plot(df["k"], df["q_n_1"], label="State 2 (q(n|2))", color="brown")
    ax2.set_title("Emission Probabilities for 'n'")
    ax2.set_xlabel("Iteration (k)")
    ax2.legend()
    ax2.grid(True, linestyle=":", alpha=0.6)

    # Subplot 3 for space
    ax3.plot(df["k"], df["q_space_0"], label="State 1 (q(space|1))", color="teal")
    ax3.plot(df["k"], df["q_space_1"], label="State 2 (q(space|2))", color="magenta")
    ax3.set_title("Emission Probabilities for Space (' ')")
    ax3.set_xlabel("Iteration (k)")
    ax3.legend()
    ax3.grid(True, linestyle=":", alpha=0.6)

    plt.tight_layout()
    plt.savefig("emission_probabilities_plot.png")
    plt.close()  # Close the figure to free memory


# Execute the plotting function
if __name__ == "__main__":
    models_dir = "models"
    # HACK: Change here to plot a different model
    file_name = "metrics_10state.csv"

    data_path = Path(models_dir) / file_name
    plot_hmm_metrics(data_path)

    print(
        "Successfully generated hill_climbing_plot.png and emission_probabilities_plot.png"
    )
